"""add school events

Revision ID: 0acd16a12f2b
Revises: df88953403f9
Create Date: 2026-07-14 01:04:12.837976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acd16a12f2b'
down_revision: Union[str, Sequence[str], None] = 'df88953403f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_events_id'), 'school_events', ['id'], unique=False)
    op.add_column('schools', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'address')
    op.drop_column('schools', 'contact_phone')
    op.drop_column('schools', 'contact_email')
    op.drop_index(op.f('ix_school_events_id'), table_name='school_events')
    op.drop_table('school_events')
    # ### end Alembic commands ###
