"""add parent complaints and substitutions

Revision ID: 0c2458e86205
Revises: 5c655eaf2a71
Create Date: 2026-07-25 23:56:45.804401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2458e86205'
down_revision: Union[str, Sequence[str], None] = '5c655eaf2a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('guardian_name', sa.String(), nullable=False),
    sa.Column('guardian_phone', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('logged_by_user_id', sa.Integer(), nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_complaints_id'), 'parent_complaints', ['id'], unique=False)
    op.create_table('substitutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timetable_slot_id', sa.Integer(), nullable=False),
    sa.Column('original_teacher_id', sa.Integer(), nullable=False),
    sa.Column('substitute_teacher_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['substitute_teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['timetable_slot_id'], ['timetable_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timetable_slot_id', 'date', name='uq_slot_date_substitution')
    )
    op.create_index(op.f('ix_substitutions_id'), 'substitutions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_substitutions_id'), table_name='substitutions')
    op.drop_table('substitutions')
    op.drop_index(op.f('ix_parent_complaints_id'), table_name='parent_complaints')
    op.drop_table('parent_complaints')
    # ### end Alembic commands ###
