"""add houses, education_level, auto class ladder, sequential sections

Revision ID: 20d31c166674
Revises: 0acd16a12f2b
Create Date: 2026-07-15 11:25:49.700073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d31c166674'
down_revision: Union[str, Sequence[str], None] = '0acd16a12f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_school_house_name')
    )
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    op.add_column('schools', sa.Column('education_level', sa.String(), nullable=True))
    op.add_column('students', sa.Column('house_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('students') as batch_op:
        batch_op.create_foreign_key('fk_students_house_id', 'houses', ['house_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'house_id')
    op.drop_column('schools', 'education_level')
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
