"""student attendance: period-wise support, register, percentage, low-attendance alerts

Revision ID: 38ba73cb62d2
Revises: b3ba9177d713
Create Date: 2026-07-26 22:50:38.421478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ba73cb62d2'
down_revision: Union[str, Sequence[str], None] = 'b3ba9177d713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records') as batch_op:
        batch_op.add_column(sa.Column('period_number', sa.Integer(), nullable=False, server_default='0'))
        batch_op.drop_constraint('uq_student_date', type_='unique')
        batch_op.create_unique_constraint('uq_student_date_period', ['student_id', 'date', 'period_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records') as batch_op:
        batch_op.drop_constraint('uq_student_date_period', type_='unique')
        batch_op.create_unique_constraint('uq_student_date', ['student_id', 'date'])
        batch_op.drop_column('period_number')
    # ### end Alembic commands ###
