"""add must_change_password and temp_password_expires_at to users

Revision ID: 515797662801
Revises: 547d08b71917
Create Date: 2026-08-01 08:02:34.333110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515797662801'
down_revision: Union[str, Sequence[str], None] = '547d08b71917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('temp_password_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_password_expires_at')
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
