"""add unique slug to schools for per-school login URLs

Revision ID: 547d08b71917
Revises: 5fcdd7a117b5
Create Date: 2026-08-01 00:44:11.544019

"""
from typing import Sequence, Union
import re

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547d08b71917'
down_revision: Union[str, Sequence[str], None] = '5fcdd7a117b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _slugify(text: str) -> str:
    text = text.strip().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = re.sub(r"-+", "-", text).strip("-")
    return text or "school"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_schools_slug'), 'schools', ['slug'], unique=True)
    # ### end Alembic commands ###

    # Backfill: every school created before this migration has no slug
    # yet. Without this, existing schools would have no login URL at
    # all — generate one now using the same rules new schools get.
    conn = op.get_bind()
    schools = conn.execute(sa.text("SELECT id, name, short_name FROM schools")).fetchall()
    used_slugs = set()
    for school_id, name, short_name in schools:
        base = _slugify(short_name) if short_name else _slugify(name)
        slug = base
        suffix = 2
        while slug in used_slugs:
            slug = f"{base}-{suffix}"
            suffix += 1
        used_slugs.add(slug)
        conn.execute(
            sa.text("UPDATE schools SET slug = :slug WHERE id = :id"),
            {"slug": slug, "id": school_id},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_slug'), table_name='schools')
    op.drop_column('schools', 'slug')
    # ### end Alembic commands ###