"""add indexes for lifecycle_status and document lookups

Revision ID: 5c655eaf2a71
Revises: 3ac09c1214e6
Create Date: 2026-07-25 18:51:36.327220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c655eaf2a71'
down_revision: Union[str, Sequence[str], None] = '3ac09c1214e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_entity_type_entity_id', 'documents', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_documents_expiry_date'), 'documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_schools_lifecycle_status'), 'schools', ['lifecycle_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_lifecycle_status'), table_name='schools')
    op.drop_index(op.f('ix_documents_expiry_date'), table_name='documents')
    op.drop_index('ix_documents_entity_type_entity_id', table_name='documents')
    # ### end Alembic commands ###
