"""add staff salary payments

Revision ID: 5fcdd7a117b5
Revises: 40eea6b7ebe5
Create Date: 2026-07-28 10:28:12.197320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fcdd7a117b5'
down_revision: Union[str, Sequence[str], None] = '40eea6b7ebe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Integer(), nullable=False),
    sa.Column('allowances', sa.Integer(), nullable=False),
    sa.Column('deductions', sa.Integer(), nullable=False),
    sa.Column('net_salary', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('paid_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['staff_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_user_id', 'month', 'year', name='uq_staff_salary_month')
    )
    op.create_index(op.f('ix_salary_payments_id'), 'salary_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_payments_id'), table_name='salary_payments')
    op.drop_table('salary_payments')
    # ### end Alembic commands ###
