"""add verified_by_platform_admin_id to documents for verification module

Revision ID: 6cf746830007
Revises: f35418b1a5b6
Create Date: 2026-07-25 11:58:00.698034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf746830007'
down_revision: Union[str, Sequence[str], None] = 'f35418b1a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('verified_by_platform_admin_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('documents') as batch_op:
        batch_op.create_foreign_key('fk_documents_verified_by_platform_admin_id', 'platform_admins', ['verified_by_platform_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'verified_by_platform_admin_id')
    # ### end Alembic commands ###
