"""add fee categories, refund model, senior_accountant and finance_manager roles

Revision ID: 6dbe903f1300
Revises: 848bb22c73ce
Create Date: 2026-08-06 05:15:09.790457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbe903f1300'
down_revision: Union[str, Sequence[str], None] = '848bb22c73ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean slate for fee_structures - fee_category_id is about to be
    # added as NOT NULL, and any existing rows have no way to satisfy
    # that (they only ever had the old free-text fee_type field).
    op.execute("DELETE FROM fee_structures")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_school_fee_category_name')
    )
    with op.batch_alter_table('fee_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_categories_id'), ['id'], unique=False)

    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('processed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('refund_method', sa.String(), nullable=True),
    sa.Column('receipt_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['fee_payments.id'], ),
    sa.ForeignKeyConstraint(['processed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_id'), ['id'], unique=False)

    with op.batch_alter_table('fee_concessions', schema=None) as batch_op:
        # server_default here (not a clean-slate delete) - existing
        # concessions may already be referenced by real invoices via
        # concession_id, so deleting them would silently break
        # historical invoice data. Every existing row just becomes a
        # regular "concession" by default, which is the correct,
        # harmless classification for anything created before this
        # split existed.
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False, server_default='concession'))

    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_structure_category', 'fee_categories', ['fee_category_id'], ['id'])
        batch_op.drop_column('fee_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_type', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('fk_structure_category', type_='foreignkey')
        batch_op.drop_column('fee_category_id')

    with op.batch_alter_table('fee_concessions', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('fee_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_categories_id'))

    op.drop_table('fee_categories')
    # ### end Alembic commands ###