"""add temp password fields and full admissions pipeline redesign

Revision ID: 848bb22c73ce
Revises: 515797662801
Create Date: 2026-08-03 16:04:49.958192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848bb22c73ce'
down_revision: Union[str, Sequence[str], None] = '515797662801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean slate for Admissions - old rows can't satisfy the new
    # NOT NULL columns below anyway (student_name/source/stage etc.
    # were never collected under the old schema).
    op.execute("DELETE FROM admission_applications")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_events_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('admission_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('admission_number_format', sa.String(), nullable=False),
    sa.Column('enable_entrance_test', sa.Boolean(), nullable=False),
    sa.Column('enable_interview', sa.Boolean(), nullable=False),
    sa.Column('required_documents_json', sa.String(), nullable=False),
    sa.Column('classes_open_json', sa.String(), nullable=False),
    sa.Column('application_fee', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    with op.batch_alter_table('admission_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admission_settings_id'), ['id'], unique=False)

    op.create_table('admission_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('conducted_at', sa.DateTime(), nullable=True),
    sa.Column('subjects_json', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    with op.batch_alter_table('admission_test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admission_test_results_id'), ['id'], unique=False)

    op.create_table('counseling_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('counselor_user_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('discussion_notes', sa.String(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ),
    sa.ForeignKeyConstraint(['counselor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counseling_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counseling_sessions_id'), ['id'], unique=False)

    op.create_table('document_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_submissions_id'), ['id'], unique=False)

    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('panel_user_ids_json', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_id'), ['id'], unique=False)

    with op.batch_alter_table('admission_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('student_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('parent_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('current_school', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('assigned_counselor_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('full_application_json', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('decision', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('decision_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('decided_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('decided_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('offer_valid_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('lost_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('converted_student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('applying_for_class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('guardian_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_adm_app_converted_student', 'students', ['converted_student_id'], ['id'])
        batch_op.create_foreign_key('fk_adm_app_counselor', 'users', ['assigned_counselor_user_id'], ['id'])
        batch_op.create_foreign_key('fk_adm_app_created_by', 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_adm_app_decided_by', 'users', ['decided_by_user_id'], ['id'])
        batch_op.drop_column('previous_school')
        batch_op.drop_column('enrolled_student_id')
        batch_op.drop_column('applicant_name')
        batch_op.drop_column('status')
        batch_op.drop_column('reviewed_by_user_id')

    with op.batch_alter_table('student_fee_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_application_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fee_structure_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_invoice_admission_app', 'admission_applications', ['admission_application_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roll_number', sa.String(), nullable=True))

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('roll_number')

    with op.batch_alter_table('student_fee_invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fee_structure_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('admission_application_id')

    with op.batch_alter_table('admission_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('applicant_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('enrolled_student_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('previous_school', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['enrolled_student_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reviewed_by_user_id'], ['id'])
        batch_op.alter_column('guardian_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('applying_for_class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('converted_student_id')
        batch_op.drop_column('lost_reason')
        batch_op.drop_column('offer_valid_until')
        batch_op.drop_column('decided_at')
        batch_op.drop_column('decided_by_user_id')
        batch_op.drop_column('decision_reason')
        batch_op.drop_column('decision')
        batch_op.drop_column('full_application_json')
        batch_op.drop_column('assigned_counselor_user_id')
        batch_op.drop_column('address')
        batch_op.drop_column('current_school')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('parent_name')
        batch_op.drop_column('student_name')
        batch_op.drop_column('source')
        batch_op.drop_column('stage')

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_id'))

    op.drop_table('interviews')
    with op.batch_alter_table('document_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_submissions_id'))

    op.drop_table('document_submissions')
    with op.batch_alter_table('counseling_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counseling_sessions_id'))

    op.drop_table('counseling_sessions')
    with op.batch_alter_table('admission_test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admission_test_results_id'))

    op.drop_table('admission_test_results')
    with op.batch_alter_table('admission_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admission_settings_id'))

    op.drop_table('admission_settings')
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_domain_events_id'))
        batch_op.drop_index(batch_op.f('ix_domain_events_event_name'))

    op.drop_table('domain_events')
    # ### end Alembic commands ###
