"""communication: bulk messaging, ptm scheduling; transport: routes, stops, student assignment

Revision ID: 853de248b104
Revises: 677b8bc701ca
Create Date: 2026-07-27 05:29:28.148748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853de248b104'
down_revision: Union[str, Sequence[str], None] = 'b4cbada938c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=False),
    sa.Column('route_number', sa.String(), nullable=True),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('driver_phone', sa.String(), nullable=True),
    sa.Column('conductor_name', sa.String(), nullable=True),
    sa.Column('conductor_phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_routes_id'), 'bus_routes', ['id'], unique=False)
    op.create_table('bus_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_name', sa.String(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('pickup_time', sa.String(), nullable=True),
    sa.Column('drop_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['bus_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_stops_id'), 'bus_stops', ['id'], unique=False)
    op.create_table('bulk_message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('target_scope', sa.String(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.String(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_message_logs_id'), 'bulk_message_logs', ['id'], unique=False)
    op.create_table('ptm_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('ptm_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ptm_schedules_id'), 'ptm_schedules', ['id'], unique=False)
    op.create_table('ptm_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptm_schedule_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('marked_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ptm_schedule_id'], ['ptm_schedules.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ptm_schedule_id', 'student_id', name='uq_ptm_student')
    )
    op.create_index(op.f('ix_ptm_attendance_id'), 'ptm_attendance', ['id'], unique=False)

    with op.batch_alter_table('announcements') as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False, server_default='administrative'))
        batch_op.add_column(sa.Column('school_class_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_announcement_class', 'school_classes', ['school_class_id'], ['id'])
        batch_op.create_foreign_key('fk_announcement_section', 'sections', ['section_id'], ['id'])

    with op.batch_alter_table('fee_structures') as batch_op:
        batch_op.add_column(sa.Column('bus_route_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_fee_structure_bus_route', 'bus_routes', ['bus_route_id'], ['id'])

    with op.batch_alter_table('students') as batch_op:
        batch_op.add_column(sa.Column('bus_route_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bus_stop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_student_bus_route', 'bus_routes', ['bus_route_id'], ['id'])
        batch_op.create_foreign_key('fk_student_bus_stop', 'bus_stops', ['bus_stop_id'], ['id'])
        batch_op.drop_column('transport_stop')
        batch_op.drop_column('transport_route')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('students') as batch_op:
        batch_op.add_column(sa.Column('transport_route', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('transport_stop', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_student_bus_route', type_='foreignkey')
        batch_op.drop_constraint('fk_student_bus_stop', type_='foreignkey')
        batch_op.drop_column('bus_stop_id')
        batch_op.drop_column('bus_route_id')

    with op.batch_alter_table('fee_structures') as batch_op:
        batch_op.drop_constraint('fk_fee_structure_bus_route', type_='foreignkey')
        batch_op.drop_column('bus_route_id')

    with op.batch_alter_table('announcements') as batch_op:
        batch_op.drop_constraint('fk_announcement_class', type_='foreignkey')
        batch_op.drop_constraint('fk_announcement_section', type_='foreignkey')
        batch_op.drop_column('section_id')
        batch_op.drop_column('school_class_id')
        batch_op.drop_column('category')

    op.drop_index(op.f('ix_ptm_attendance_id'), table_name='ptm_attendance')
    op.drop_table('ptm_attendance')
    op.drop_index(op.f('ix_ptm_schedules_id'), table_name='ptm_schedules')
    op.drop_table('ptm_schedules')
    op.drop_index(op.f('ix_bulk_message_logs_id'), table_name='bulk_message_logs')
    op.drop_table('bulk_message_logs')
    op.drop_index(op.f('ix_bus_stops_id'), table_name='bus_stops')
    op.drop_table('bus_stops')
    op.drop_index(op.f('ix_bus_routes_id'), table_name='bus_routes')
    op.drop_table('bus_routes')
