"""student management: extended profile, TC generation, re-admission

Revision ID: a683230c3182
Revises: 0c2458e86205
Create Date: 2026-07-26 01:55:18.176173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a683230c3182'
down_revision: Union[str, Sequence[str], None] = '0c2458e86205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardians', sa.Column('alternate_phone', sa.String(), nullable=True))
    op.add_column('guardians', sa.Column('annual_income', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('religion', sa.String(), nullable=True))
    op.add_column('students', sa.Column('nationality', sa.String(), nullable=True))
    op.add_column('students', sa.Column('mother_tongue', sa.String(), nullable=True))
    op.add_column('students', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('students', sa.Column('medical_notes', sa.String(), nullable=True))
    op.add_column('students', sa.Column('transport_route', sa.String(), nullable=True))
    op.add_column('students', sa.Column('transport_stop', sa.String(), nullable=True))
    op.add_column('students', sa.Column('date_of_leaving', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('leaving_reason', sa.String(), nullable=True))
    op.add_column('students', sa.Column('tc_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'tc_number')
    op.drop_column('students', 'leaving_reason')
    op.drop_column('students', 'date_of_leaving')
    op.drop_column('students', 'transport_stop')
    op.drop_column('students', 'transport_route')
    op.drop_column('students', 'medical_notes')
    op.drop_column('students', 'photo_url')
    op.drop_column('students', 'mother_tongue')
    op.drop_column('students', 'nationality')
    op.drop_column('students', 'religion')
    op.drop_column('guardians', 'annual_income')
    op.drop_column('guardians', 'alternate_phone')
    # ### end Alembic commands ###
