"""add register school PRD foundation

Revision ID: ad878fcbbf22
Revises: cd5771d4887c
Create Date: 2026-07-25 00:51:46.121253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad878fcbbf22'
down_revision: Union[str, Sequence[str], None] = 'cd5771d4887c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_school_department_name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('school_infrastructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('campus_area', sa.String(), nullable=True),
    sa.Column('number_of_classrooms', sa.Integer(), nullable=True),
    sa.Column('number_of_labs', sa.Integer(), nullable=True),
    sa.Column('has_library', sa.Boolean(), nullable=True),
    sa.Column('sports_facilities', sa.String(), nullable=True),
    sa.Column('has_transport', sa.Boolean(), nullable=True),
    sa.Column('has_hostel', sa.Boolean(), nullable=True),
    sa.Column('has_medical_room', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_index(op.f('ix_school_infrastructure_id'), 'school_infrastructure', ['id'], unique=False)
    op.create_table('school_organization_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('date_format', sa.String(), nullable=True),
    sa.Column('number_format', sa.String(), nullable=True),
    sa.Column('week_start_day', sa.String(), nullable=True),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_index(op.f('ix_school_organization_settings_id'), 'school_organization_settings', ['id'], unique=False)
    op.create_table('school_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before_snapshot', sa.String(), nullable=True),
    sa.Column('after_snapshot', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_audit_logs_id'), 'school_audit_logs', ['id'], unique=False)
    op.add_column('documents', sa.Column('issue_date', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('verified_by_user_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('reminder_60_day_sent', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('reminder_30_day_sent', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('reminder_7_day_sent', sa.Boolean(), nullable=True))
    with op.batch_alter_table('documents') as batch_op:
        batch_op.create_foreign_key('fk_documents_verified_by_user_id', 'users', ['verified_by_user_id'], ['id'])
    op.add_column('schools', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('school_type', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('school_category', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('year_established', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('motto', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('state_board_name', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('udise_code', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('affiliation_number', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('affiliation_valid_from', sa.Date(), nullable=True))
    op.add_column('schools', sa.Column('affiliation_valid_to', sa.Date(), nullable=True))
    op.add_column('schools', sa.Column('recognition_number', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('trust_registration_number', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('pan_number', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('gst_number', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('address_line_2', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('pincode', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('google_maps_url', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('school_timing_start', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('school_timing_end', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('working_days', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('medium_of_instruction', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('grading_system', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('attendance_min_percentage', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('promotion_policy', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('banner_url', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('secondary_color', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('letterhead_url', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('seal_url', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('id_card_template', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('report_card_template', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('certificate_template', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('billing_cycle', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('pricing_model', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('contract_start_date', sa.Date(), nullable=True))
    op.add_column('schools', sa.Column('contract_end_date', sa.Date(), nullable=True))
    op.add_column('schools', sa.Column('trial_ends_at', sa.Date(), nullable=True))
    op.add_column('schools', sa.Column('lifecycle_status', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('verified_by_platform_admin_id', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('schools', sa.Column('rejection_reason', sa.String(), nullable=True))
    with op.batch_alter_table('schools') as batch_op:
        batch_op.create_foreign_key('fk_schools_verified_by_platform_admin_id', 'platform_admins', ['verified_by_platform_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_column('schools', 'rejection_reason')
    op.drop_column('schools', 'verified_at')
    op.drop_column('schools', 'verified_by_platform_admin_id')
    op.drop_column('schools', 'lifecycle_status')
    op.drop_column('schools', 'trial_ends_at')
    op.drop_column('schools', 'contract_end_date')
    op.drop_column('schools', 'contract_start_date')
    op.drop_column('schools', 'pricing_model')
    op.drop_column('schools', 'billing_cycle')
    op.drop_column('schools', 'certificate_template')
    op.drop_column('schools', 'report_card_template')
    op.drop_column('schools', 'id_card_template')
    op.drop_column('schools', 'seal_url')
    op.drop_column('schools', 'letterhead_url')
    op.drop_column('schools', 'secondary_color')
    op.drop_column('schools', 'banner_url')
    op.drop_column('schools', 'promotion_policy')
    op.drop_column('schools', 'attendance_min_percentage')
    op.drop_column('schools', 'grading_system')
    op.drop_column('schools', 'medium_of_instruction')
    op.drop_column('schools', 'working_days')
    op.drop_column('schools', 'school_timing_end')
    op.drop_column('schools', 'school_timing_start')
    op.drop_column('schools', 'google_maps_url')
    op.drop_column('schools', 'website_url')
    op.drop_column('schools', 'pincode')
    op.drop_column('schools', 'address_line_2')
    op.drop_column('schools', 'gst_number')
    op.drop_column('schools', 'pan_number')
    op.drop_column('schools', 'trust_registration_number')
    op.drop_column('schools', 'recognition_number')
    op.drop_column('schools', 'affiliation_valid_to')
    op.drop_column('schools', 'affiliation_valid_from')
    op.drop_column('schools', 'affiliation_number')
    op.drop_column('schools', 'udise_code')
    op.drop_column('schools', 'state_board_name')
    op.drop_column('schools', 'motto')
    op.drop_column('schools', 'year_established')
    op.drop_column('schools', 'school_category')
    op.drop_column('schools', 'school_type')
    op.drop_column('schools', 'short_name')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'reminder_7_day_sent')
    op.drop_column('documents', 'reminder_30_day_sent')
    op.drop_column('documents', 'reminder_60_day_sent')
    op.drop_column('documents', 'verified_at')
    op.drop_column('documents', 'verified_by_user_id')
    op.drop_column('documents', 'expiry_date')
    op.drop_column('documents', 'issue_date')
    op.drop_index(op.f('ix_school_audit_logs_id'), table_name='school_audit_logs')
    op.drop_table('school_audit_logs')
    op.drop_index(op.f('ix_school_organization_settings_id'), table_name='school_organization_settings')
    op.drop_table('school_organization_settings')
    op.drop_index(op.f('ix_school_infrastructure_id'), table_name='school_infrastructure')
    op.drop_table('school_infrastructure')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
