"""examinations: exam setup, marks entry, correction workflow, report cards

Revision ID: b3ba9177d713
Revises: b565a6669ad1
Create Date: 2026-07-26 19:02:08.145414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ba9177d713'
down_revision: Union[str, Sequence[str], None] = 'b565a6669ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    op.create_table('exam_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('passing_marks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'school_class_id', 'subject_id', name='uq_exam_class_subject')
    )
    op.create_index(op.f('ix_exam_schedules_id'), 'exam_schedules', ['id'], unique=False)
    op.create_table('exam_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_schedule_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('marks_obtained', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=True),
    sa.Column('entered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entered_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_schedule_id'], ['exam_schedules.id'], ),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_schedule_id', 'student_id', name='uq_schedule_student')
    )
    op.create_index(op.f('ix_exam_marks_id'), 'exam_marks', ['id'], unique=False)
    op.create_table('report_card_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_exam_student_signature')
    )
    op.create_index(op.f('ix_report_card_signatures_id'), 'report_card_signatures', ['id'], unique=False)
    op.create_table('marks_correction_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_marks_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('old_marks', sa.Integer(), nullable=True),
    sa.Column('requested_marks', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exam_marks_id'], ['exam_marks.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marks_correction_requests_id'), 'marks_correction_requests', ['id'], unique=False)
    with op.batch_alter_table('school_classes') as batch_op:
        batch_op.create_unique_constraint('uq_class_year_name', ['academic_year_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_classes') as batch_op:
        batch_op.drop_constraint('uq_class_year_name', type_='unique')
    op.drop_index(op.f('ix_marks_correction_requests_id'), table_name='marks_correction_requests')
    op.drop_table('marks_correction_requests')
    op.drop_index(op.f('ix_report_card_signatures_id'), table_name='report_card_signatures')
    op.drop_table('report_card_signatures')
    op.drop_index(op.f('ix_exam_marks_id'), table_name='exam_marks')
    op.drop_table('exam_marks')
    op.drop_index(op.f('ix_exam_schedules_id'), table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_index(op.f('ix_exams_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
