"""fee management: concessions, waivers, late fees, receipts, reporting

Revision ID: b4cbada938c7
Revises: 38ba73cb62d2
Create Date: 2026-07-27 00:03:25.905517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4cbada938c7'
down_revision: Union[str, Sequence[str], None] = '38ba73cb62d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_concessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('concession_type', sa.String(), nullable=False),
    sa.Column('discount_type', sa.String(), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_concessions_id'), 'fee_concessions', ['id'], unique=False)
    op.create_table('fee_waiver_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('waiver_amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['student_fee_invoices.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_waiver_requests_id'), 'fee_waiver_requests', ['id'], unique=False)
    with op.batch_alter_table('fee_payments') as batch_op:
        batch_op.add_column(sa.Column('receipt_number', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_fee_payments_receipt_number', ['receipt_number'])
    with op.batch_alter_table('fee_structures') as batch_op:
        batch_op.add_column(sa.Column('late_fee_amount', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('late_fee_grace_days', sa.Integer(), nullable=False, server_default='0'))
    with op.batch_alter_table('student_fee_invoices') as batch_op:
        batch_op.add_column(sa.Column('concession_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('concession_amount', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_foreign_key('fk_invoice_concession', 'fee_concessions', ['concession_id'], ['id'])
    op.add_column('students', sa.Column('is_rte', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_fee_invoices') as batch_op:
        batch_op.drop_constraint('fk_invoice_concession', type_='foreignkey')
        batch_op.drop_column('concession_amount')
        batch_op.drop_column('concession_id')

    with op.batch_alter_table('fee_structures') as batch_op:
        batch_op.drop_column('late_fee_grace_days')
        batch_op.drop_column('late_fee_amount')

    with op.batch_alter_table('fee_payments') as batch_op:
        batch_op.drop_constraint('uq_fee_payments_receipt_number', type_='unique')
        batch_op.drop_column('receipt_number')
    op.drop_index(op.f('ix_fee_waiver_requests_id'), table_name='fee_waiver_requests')
    op.drop_table('fee_waiver_requests')
    op.drop_index(op.f('ix_fee_concessions_id'), table_name='fee_concessions')
    op.drop_table('fee_concessions')
    # ### end Alembic commands ###
