"""add coordinates to school and bus stops for map display

Revision ID: b520929abe52
Revises: ffde5851ef0f
Create Date: 2026-07-27 12:16:56.721052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b520929abe52'
down_revision: Union[str, Sequence[str], None] = 'ffde5851ef0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bus_stops', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('bus_stops', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'longitude')
    op.drop_column('schools', 'latitude')
    op.drop_column('bus_stops', 'longitude')
    op.drop_column('bus_stops', 'latitude')
    # ### end Alembic commands ###
