"""add stage to school classes

Revision ID: cd5771d4887c
Revises: 20d31c166674
Create Date: 2026-07-16 02:51:01.319316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5771d4887c'
down_revision: Union[str, Sequence[str], None] = '20d31c166674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_classes', sa.Column('stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_classes', 'stage')
    # ### end Alembic commands ###
