"""add father_name, mother_name to students

Revision ID: d514fd04d872
Revises: a683230c3182
Create Date: 2026-07-26 12:49:41.947688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd514fd04d872'
down_revision: Union[str, Sequence[str], None] = 'a683230c3182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('father_name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('mother_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'mother_name')
    op.drop_column('students', 'father_name')
    # ### end Alembic commands ###
