"""add platform layer: platform admins, feature flags, audit logs, school subscription fields

Revision ID: df88953403f9
Revises: db5ffc3728f1
Create Date: 2026-07-12 12:05:16.347126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df88953403f9'
down_revision: Union[str, Sequence[str], None] = 'db5ffc3728f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
