"""add school registration wizard draft fields

Revision ID: f35418b1a5b6
Revises: ad878fcbbf22
Create Date: 2026-07-25 01:17:36.419688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35418b1a5b6'
down_revision: Union[str, Sequence[str], None] = 'ad878fcbbf22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('selected_stages', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('trust_name', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('chairman_name', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('managing_director_name', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('pending_admin_full_name', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('pending_admin_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'pending_admin_email')
    op.drop_column('schools', 'pending_admin_full_name')
    op.drop_column('schools', 'managing_director_name')
    op.drop_column('schools', 'chairman_name')
    op.drop_column('schools', 'trust_name')
    op.drop_column('schools', 'selected_stages')
    # ### end Alembic commands ###
