"""staff HR management: extended profile, leave management, attendance reporting

Revision ID: fa44f3580a0d
Revises: d514fd04d872
Create Date: 2026-07-26 17:46:18.559477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa44f3580a0d'
down_revision: Union[str, Sequence[str], None] = 'd514fd04d872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_applications_id'), 'leave_applications', ['id'], unique=False)
    op.add_column('staff_profiles', sa.Column('department', sa.String(), nullable=True))
    op.add_column('staff_profiles', sa.Column('qualification', sa.String(), nullable=True))
    op.add_column('staff_profiles', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('staff_profiles', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('staff_profiles', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('staff_profiles', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.add_column('staff_profiles', sa.Column('emergency_contact_relation', sa.String(), nullable=True))
    op.add_column('staff_profiles', sa.Column('bank_account_holder_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_profiles', 'bank_account_holder_name')
    op.drop_column('staff_profiles', 'emergency_contact_relation')
    op.drop_column('staff_profiles', 'emergency_contact_phone')
    op.drop_column('staff_profiles', 'emergency_contact_name')
    op.drop_column('staff_profiles', 'photo_url')
    op.drop_column('staff_profiles', 'experience_years')
    op.drop_column('staff_profiles', 'qualification')
    op.drop_column('staff_profiles', 'department')
    op.drop_index(op.f('ix_leave_applications_id'), table_name='leave_applications')
    op.drop_table('leave_applications')
    # ### end Alembic commands ###
